# Change these first
owner: alexjp # Your GitHub organization or username, where this repository lives
repo: wetest # The name of this repository
delay: 360000 # 1 hour

sites:
  - name: Weticlient
    url: https://weticlient.ddns.net
  - name: Alternative
    url: http://wetest.mine.nu

status-website:  
  baseUrl: /wetest
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Wetest website uptime
  introTitle: "**WETEST Uptime** uptime monitor and status page for WETEST web services, powered entirely by GitHub."
  introMessage: "**Status** page of **WETEST** websites: [Weticlient](https://weticlient.ddns.net)"
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/alexjp/wetest

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
