# Change these first
owner: alexjp # Your GitHub organization or username, where this repository lives
repo: wetest # The name of this repository

sites:
  - name: Weticlient
    url: https://weticlient.ddns.net
  - name: Alternative
    url: http://wetest.mine.nu

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /wetest
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Wetest website uptime
  introTitle: "**WETEST Uptime** uptime monitor and status page for WETEST web services, powered entirely by GitHub."
  introMessage: "**Status** page of **WETEST** websites: [Weticlient](https://weticlient.ddns.net)"
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/alexjp/wetest

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
